#!/usr/bin/env bash

# if the query isn't provided as an arg, grab it with 'dmenu'
if [[ -z "$1" ]]; then
  query=$( printf "" | dmenu -b -p "Search YouTube:" )
else
	query="$1"
fi

# if query was given, replace any spaces with '+' to match YouTube's search syntax
[ -z "${query}" ] && echo "No query given. Exiting." && exit 1
query="${query// /+}"

# set the variable below to your API key if desired.
# YT_API_KEY=""
# otherwise, set your YT_API_KEY file location below
YT_API_KEY="$( cat "${HOME}/lib/api_keys/YT_API_KEY" )"
urlstring="https://www.googleapis.com/youtube/v3/search?part=snippet&q=${query}&type=video&maxResults=20&key=${YT_API_KEY}"

# get the video url by filtering the search results with 'jq' and sending them to 'dmenu'
# the url of the video chosen is then given to 'mpv'
video="$( curl -s "${urlstring}" \
	| jq -r '.items[] | "\(.snippet.channelTitle) => \(.snippet.title) => youtu.be/\(.id.videoId)"' \
	| dmenu -b -i -p "Select Video -" -l 20 \
	| awk '{print $NF}' \
)"

[ -z "${video}" ] && echo "No video selected. Exiting." && exit 1
video="https://${video}"

mpv --no-terminal -- "${video}"
