#!/usr/bin/env sh
[ -z "$1" ] && query=$(echo | dmenu -p "Search YT Video:") \
	&& query=$(echo "$query" | tr ' ' '+')
[ -n "$1" ] && query=$(echo "$@" | tr ' ' '+')

query=$(echo "$@" | tr ' ' '+')

# YT_API_KEY location, again can change this , check the README if you find in trouble
YT_API_KEY="$( cat "${HOME}"/.api_keys/YT_API_KEY )"

[ -z "$YT_API_KEY" ] && printf "you need to define a api key\\n" && exit

urlstring="https://www.googleapis.com/youtube/v3/search?part=snippet&q=${query}&type=video&maxResults=20&key=${YT_API_KEY}"

a=$(curl -4 -sf "${urlstring}" \
	| jq -r '.items[] | "\(.snippet.channelTitle) => \(.snippet.title) => youtu.be/\(.id.videoId)"')

while true; do
	b=$(echo "$a" | dmenu -i -p 'Select Video -' -l 20 | awk '{print $NF}')
	[ -z "$b" ] && exit || mpv "https://$b" 1>/dev/null # see if errors happened
done &
