#!/bin/sh

[ -z "$1" ] && printf "put expression to search: " \
&& read -r eso && query="$(echo "$eso" | tr ' ' '+')"

[ -n "$1" ] && query="$(echo "$@" | tr ' ' '+')"

# YT_API_KEY location, you can change this of course or put the api directly here replacing the following line with your key i.e.: YT_API_KEY=''
YT_API_KEY="$( cat "${HOME}"/.api_keys/YT_API_KEY )"

[ -z "$YT_API_KEY" ] && printf "you need to define an api key\\n" && exit

urlstring="https://www.googleapis.com/youtube/v3/search?part=snippet&q=${query}&type=video&maxResults=20&key=${YT_API_KEY}"

a="$( curl -s "${urlstring}" \
	| jq -r '.items[] | "\(.snippet.channelTitle) => \(.snippet.title) youtu.be/\(.id.videoId)"')"
	
while true; do
	b="$( echo "$a" | fzf --reverse --cycle --with-nth='1..-2' +m | awk '{print $NF}')" \
	&& [ -z "$b" ] && exit || mpv "https://$b" >/dev/null
done


