#!/usr/bin/env bash

# if the query isn't provided as an arg, grab it with 'read'
if [[ -z "$1" ]]; then
  read -rp "Search YouTube: " query
else
	query="$1"
fi

# if query was given, replace any spaces with '+' to match YouTube's search syntax
[ -z "${query}" ] && echo "No query given. Exiting." && exit 1
query="${query// /+}"

# YT_API_KEY location
YT_API_KEY="$( cat "${HOME}/lib/api_keys/YT_API_KEY" )"
urlstring="https://www.googleapis.com/youtube/v3/search?part=snippet&q=${query}&type=video&maxResults=20&key=${YT_API_KEY}"

# get the video url by filtering the search results with 'jq' and sending them to 'fzf'
# the url of the video chosen is then given to 'mpv'
video="$( curl -s "${urlstring}" \
	| jq -r '.items[] | "\(.snippet.channelTitle) => \(.snippet.title) youtu.be/\(.id.videoId)"' \
	| fzf --with-nth='1..-2' +m --height=82% \
	| awk '{print $NF}' \
)"

[ -z "${video}" ] && echo "No video selected. Exiting." && exit 1
video="https://${video}"

mpv --no-terminal -- "${video}"
