#!/bin/sh

query="$(echo "$@" | tr ' ' '+')"

# YT_API_KEY location, you can change this of course or put the api directly here replacing the following line with your key i.e.: YT_API_KEY=''
YT_API_KEY="$( cat "${HOME}"/.api_keys/YT_API_KEY )"

[ -z "$YT_API_KEY" ] && printf "you need to define an api key\\n" && exit

urlstring="https://www.googleapis.com/youtube/v3/search?part=snippet&q=${query}&type=video&maxResults=20&key=${YT_API_KEY}"

a="$( curl -s "${urlstring}" \
	| jq -r '.items[] | "\(.snippet.channelTitle) => \(.snippet.title) youtu.be/\(.id.videoId)"' \
	| fzf --reverse --cycle --with-nth='1..-2' +m \
	| awk '{print $NF}' \
)"

#allow you to exit cleanly if no value is passed 
[ -n "$a" ] && mpv "https://$a"
