#!/usr/bin/env sh

# if the query isn't provided as an arg, grab it with 'rofi'
if [[ -z "$1" ]]; then
  query=$( rofi -dmenu -mesg "Search YouTube" -matching "fuzzy")
else
	query="$1"
fi

# if query was given, replace any spaces with '+' to match YouTube's search syntax
if [[ "${query}" ]]; then
	query="${query// /+}"
else
	echo "No query given. Exiting."; exit 1
fi

# set the variable below to your API key if desired.
# YT_API_KEY=""
# otherwise, set your YT_API_KEY file location below
YT_API_KEY="$( cat "${HOME}"/.api_keys/YT_API_KEY )"
urlstring="https://www.googleapis.com/youtube/v3/search?part=snippet&q=${query}&type=video&maxResults=20&key=${YT_API_KEY}"

# get the video url by filtering the search results with 'jq' and sending them to dmenu
# the url of the video chosen is then given to 'mpv'
video="$( curl -s "${urlstring}" \
	| jq -r '.items[] | "\(.snippet.channelTitle) => \(.snippet.title) => youtu.be/\(.id.videoId)"' \
	| rofi -dmenu \
	| awk '{print $NF}' \
)"

if [[ "${video}" ]]; then
	video="https://${video}"
else
	echo "No video selected. Exiting."; exit 1
fi

mpv -- "${video}"
